# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\eric6ProDir\Demo\ProbePara.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from widget.mplcanvaswraper import MplCanvasProbeWraper

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(QtGui.QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(835, 450)
        Dialog.setSizeGripEnabled(True)
        self.widget = MplCanvasProbeWraper(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 591, 391))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.widget1 = QtGui.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(611, 11, 201, 391))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_9 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.label_3 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_12 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.label_11 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.label_10 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.label_5 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.m_freqCenter = QtGui.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_freqCenter.setFont(font)
        self.m_freqCenter.setObjectName(_fromUtf8("m_freqCenter"))
        self.verticalLayout_2.addWidget(self.m_freqCenter)
        self.m_bwby6 = QtGui.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_bwby6.setFont(font)
        self.m_bwby6.setObjectName(_fromUtf8("m_bwby6"))
        self.verticalLayout_2.addWidget(self.m_bwby6)
        self.m_lowFreqby6 = QtGui.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_lowFreqby6.setFont(font)
        self.m_lowFreqby6.setObjectName(_fromUtf8("m_lowFreqby6"))
        self.verticalLayout_2.addWidget(self.m_lowFreqby6)
        self.m_highFreqby6 = QtGui.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_highFreqby6.setFont(font)
        self.m_highFreqby6.setObjectName(_fromUtf8("m_highFreqby6"))
        self.verticalLayout_2.addWidget(self.m_highFreqby6)
        self.m_bwby20 = QtGui.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_bwby20.setFont(font)
        self.m_bwby20.setObjectName(_fromUtf8("m_bwby20"))
        self.verticalLayout_2.addWidget(self.m_bwby20)
        self.m_lowFreqby20 = QtGui.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_lowFreqby20.setFont(font)
        self.m_lowFreqby20.setObjectName(_fromUtf8("m_lowFreqby20"))
        self.verticalLayout_2.addWidget(self.m_lowFreqby20)
        self.m_highFreqby20 = QtGui.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_highFreqby20.setFont(font)
        self.m_highFreqby20.setObjectName(_fromUtf8("m_highFreqby20"))
        self.verticalLayout_2.addWidget(self.m_highFreqby20)
        self.m_probeSense = QtGui.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_probeSense.setFont(font)
        self.m_probeSense.setObjectName(_fromUtf8("m_probeSense"))
        self.verticalLayout_2.addWidget(self.m_probeSense)
        self.m_bw = QtGui.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_bw.setFont(font)
        self.m_bw.setObjectName(_fromUtf8("m_bw"))
        self.verticalLayout_2.addWidget(self.m_bw)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.widget2 = QtGui.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(10, 420, 591, 25))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.m_fromFreq = QtGui.QDoubleSpinBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_fromFreq.setFont(font)
        self.m_fromFreq.setObjectName(_fromUtf8("m_fromFreq"))
        self.horizontalLayout.addWidget(self.m_fromFreq)
        self.label_7 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.m_toFreq = QtGui.QDoubleSpinBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_toFreq.setFont(font)
        self.m_toFreq.setObjectName(_fromUtf8("m_toFreq"))
        self.horizontalLayout.addWidget(self.m_toFreq)
        self.label_8 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.m_calulateBtn = QtGui.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_calulateBtn.setFont(font)
        self.m_calulateBtn.setObjectName(_fromUtf8("m_calulateBtn"))
        self.horizontalLayout.addWidget(self.m_calulateBtn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "探头中心频率", None))
        self.label_2.setText(_translate("Dialog", "-6dB相对带宽", None))
        self.label_9.setText(_translate("Dialog", "-6dB低频", None))
        self.label_3.setText(_translate("Dialog", "-6dB高频", None))
        self.label_12.setText(_translate("Dialog", "-20dB相对带宽", None))
        self.label_11.setText(_translate("Dialog", "-20dB低频", None))
        self.label_10.setText(_translate("Dialog", "-20dB高频", None))
        self.label_5.setText(_translate("Dialog", "脉冲回波灵敏度", None))
        self.label_6.setText(_translate("Dialog", "脉冲宽度", None))
        self.label_4.setText(_translate("Dialog", "设置频率计算范围：", None))
        self.label_7.setText(_translate("Dialog", "MHz", None))
        self.label_8.setText(_translate("Dialog", "MHz", None))
        self.m_calulateBtn.setText(_translate("Dialog", "计算", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

