# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\eric6ProDir\Demo\ProbeBeam.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from widget.mplcanvaswraper import MplCanvasCWraper

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(QtGui.QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1196, 671)
        Dialog.setSizeGripEnabled(True)
        self.m_xyScanWidget = MplCanvasCWraper(Dialog)
        self.m_xyScanWidget.setGeometry(QtCore.QRect(10, 360, 571, 301))
        self.m_xyScanWidget.setObjectName(_fromUtf8("m_xyScanWidget"))
        self.m_yzScanWidget = MplCanvasCWraper(Dialog)
        self.m_yzScanWidget.setGeometry(QtCore.QRect(620, 30, 561, 301))
        self.m_yzScanWidget.setObjectName(_fromUtf8("m_yzScanWidget"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 340, 221, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(620, 10, 221, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.m_xzScanWidget = MplCanvasCWraper(Dialog)
        self.m_xzScanWidget.setGeometry(QtCore.QRect(10, 30, 571, 301))
        self.m_xzScanWidget.setObjectName(_fromUtf8("m_xzScanWidget"))
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(620, 370, 511, 271))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.m_focalDisSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_focalDisSBD.setObjectName(_fromUtf8("m_focalDisSBD"))
        self.horizontalLayout.addWidget(self.m_focalDisSBD)
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.m_focalLengthSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_focalLengthSBD.setObjectName(_fromUtf8("m_focalLengthSBD"))
        self.horizontalLayout.addWidget(self.m_focalLengthSBD)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_14 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_2.addWidget(self.label_14)
        self.m_focalWidthXSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_focalWidthXSBD.setObjectName(_fromUtf8("m_focalWidthXSBD"))
        self.horizontalLayout_2.addWidget(self.m_focalWidthXSBD)
        self.label_7 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.m_focalWidthYSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_focalWidthYSBD.setObjectName(_fromUtf8("m_focalWidthYSBD"))
        self.horizontalLayout_2.addWidget(self.m_focalWidthYSBD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_15 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_3.addWidget(self.label_15)
        self.m_beamAngleXSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_beamAngleXSBD.setObjectName(_fromUtf8("m_beamAngleXSBD"))
        self.horizontalLayout_3.addWidget(self.m_beamAngleXSBD)
        self.label_9 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.m_beamAngleYSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_beamAngleYSBD.setObjectName(_fromUtf8("m_beamAngleYSBD"))
        self.horizontalLayout_3.addWidget(self.m_beamAngleYSBD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.m_beamWidth3XSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_beamWidth3XSBD.setObjectName(_fromUtf8("m_beamWidth3XSBD"))
        self.horizontalLayout_4.addWidget(self.m_beamWidth3XSBD)
        self.label_12 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.m_beamWidth6XSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_beamWidth6XSBD.setObjectName(_fromUtf8("m_beamWidth6XSBD"))
        self.horizontalLayout_4.addWidget(self.m_beamWidth6XSBD)
        self.label_13 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.m_beamWidth12XSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_beamWidth12XSBD.setObjectName(_fromUtf8("m_beamWidth12XSBD"))
        self.horizontalLayout_4.addWidget(self.m_beamWidth12XSBD)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_17 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_5.addWidget(self.label_17)
        self.label_19 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_5.addWidget(self.label_19)
        self.m_beamWidth3YSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_beamWidth3YSBD.setObjectName(_fromUtf8("m_beamWidth3YSBD"))
        self.horizontalLayout_5.addWidget(self.m_beamWidth3YSBD)
        self.label_16 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_5.addWidget(self.label_16)
        self.m_beamWidth6YSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_beamWidth6YSBD.setObjectName(_fromUtf8("m_beamWidth6YSBD"))
        self.horizontalLayout_5.addWidget(self.m_beamWidth6YSBD)
        self.label_18 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_5.addWidget(self.label_18)
        self.m_beamWidth12YSBD = QtGui.QDoubleSpinBox(self.widget)
        self.m_beamWidth12YSBD.setObjectName(_fromUtf8("m_beamWidth12YSBD"))
        self.horizontalLayout_5.addWidget(self.m_beamWidth12YSBD)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_2.setText(_translate("Dialog", "平行声束方向X-Y平面焦区结束处C扫图像", None))
        self.label_3.setText(_translate("Dialog", "平行声束方向X-Z平面C扫图像", None))
        self.label_4.setText(_translate("Dialog", "平行声束方向X-Y平面焦点处C扫图像", None))
        self.label.setText(_translate("Dialog", "焦距", None))
        self.label_5.setText(_translate("Dialog", "焦区长度", None))
        self.label_6.setText(_translate("Dialog", "焦区宽度  ", None))
        self.label_14.setText(_translate("Dialog", "X", None))
        self.label_7.setText(_translate("Dialog", "Y", None))
        self.label_8.setText(_translate("Dialog", "声束扩散角", None))
        self.label_15.setText(_translate("Dialog", "X", None))
        self.label_9.setText(_translate("Dialog", "Y", None))
        self.label_10.setText(_translate("Dialog", "声束宽度 X", None))
        self.label_11.setText(_translate("Dialog", "-3DB", None))
        self.label_12.setText(_translate("Dialog", "-6DB", None))
        self.label_13.setText(_translate("Dialog", "-12DB", None))
        self.label_17.setText(_translate("Dialog", "声束宽度 Y", None))
        self.label_19.setText(_translate("Dialog", "-3DB", None))
        self.label_16.setText(_translate("Dialog", "-6DB", None))
        self.label_18.setText(_translate("Dialog", "-12DB", None))

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

