# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\eric6ProDir\Demo\ProbePara.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from widget.mplcanvaswraper import MplCanvasProbeWraper

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(QtGui.QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(973, 437)
        Dialog.setSizeGripEnabled(True)
        self.widget = MplCanvasProbeWraper(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 591, 411))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.m_calulateBtn = QtGui.QPushButton(Dialog)
        self.m_calulateBtn.setGeometry(QtCore.QRect(610, 110, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_calulateBtn.setFont(font)
        self.m_calulateBtn.setObjectName(_fromUtf8("m_calulateBtn"))
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(610, 10, 343, 91))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.m_rawCurve = QtGui.QRadioButton(self.layoutWidget)
        self.m_rawCurve.setChecked(True)
        self.m_rawCurve.setObjectName(_fromUtf8("m_rawCurve"))
        self.horizontalLayout_3.addWidget(self.m_rawCurve)
        self.m_fftCurve = QtGui.QRadioButton(self.layoutWidget)
        self.m_fftCurve.setObjectName(_fromUtf8("m_fftCurve"))
        self.horizontalLayout_3.addWidget(self.m_fftCurve)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.m_fromFreq = QtGui.QDoubleSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_fromFreq.setFont(font)
        self.m_fromFreq.setObjectName(_fromUtf8("m_fromFreq"))
        self.horizontalLayout.addWidget(self.m_fromFreq)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.m_toFreq = QtGui.QDoubleSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_toFreq.setFont(font)
        self.m_toFreq.setObjectName(_fromUtf8("m_toFreq"))
        self.horizontalLayout.addWidget(self.m_toFreq)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_2.addWidget(self.label_14)
        self.m_fromTime = QtGui.QDoubleSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_fromTime.setFont(font)
        self.m_fromTime.setObjectName(_fromUtf8("m_fromTime"))
        self.horizontalLayout_2.addWidget(self.m_fromTime)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_2.addWidget(self.label_13)
        self.m_toTime = QtGui.QDoubleSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_toTime.setFont(font)
        self.m_toTime.setObjectName(_fromUtf8("m_toTime"))
        self.horizontalLayout_2.addWidget(self.m_toTime)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtGui.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(610, 150, 241, 271))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.m_highFreqby20 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_highFreqby20.setFont(font)
        self.m_highFreqby20.setObjectName(_fromUtf8("m_highFreqby20"))
        self.gridLayout.addWidget(self.m_highFreqby20, 6, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.m_bwby20 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_bwby20.setFont(font)
        self.m_bwby20.setObjectName(_fromUtf8("m_bwby20"))
        self.gridLayout.addWidget(self.m_bwby20, 4, 1, 1, 1)
        self.m_bwby6 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_bwby6.setFont(font)
        self.m_bwby6.setObjectName(_fromUtf8("m_bwby6"))
        self.gridLayout.addWidget(self.m_bwby6, 1, 1, 1, 1)
        self.m_lowFreqby6 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_lowFreqby6.setFont(font)
        self.m_lowFreqby6.setObjectName(_fromUtf8("m_lowFreqby6"))
        self.gridLayout.addWidget(self.m_lowFreqby6, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.m_lowFreqby20 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_lowFreqby20.setFont(font)
        self.m_lowFreqby20.setObjectName(_fromUtf8("m_lowFreqby20"))
        self.gridLayout.addWidget(self.m_lowFreqby20, 5, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.m_freqCenter = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_freqCenter.setFont(font)
        self.m_freqCenter.setObjectName(_fromUtf8("m_freqCenter"))
        self.gridLayout.addWidget(self.m_freqCenter, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.m_highFreqby6 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_highFreqby6.setFont(font)
        self.m_highFreqby6.setObjectName(_fromUtf8("m_highFreqby6"))
        self.gridLayout.addWidget(self.m_highFreqby6, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.m_probeSense = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_probeSense.setFont(font)
        self.m_probeSense.setObjectName(_fromUtf8("m_probeSense"))
        self.gridLayout.addWidget(self.m_probeSense, 7, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.m_bw = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_bw.setFont(font)
        self.m_bw.setObjectName(_fromUtf8("m_bw"))
        self.gridLayout.addWidget(self.m_bw, 8, 1, 1, 1)
        self.m_calulateBtn.raise_()
        self.widget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.m_calulateBtn.setText(_translate("Dialog", "计算", None))
        self.m_rawCurve.setText(_translate("Dialog", "原始波形", None))
        self.m_fftCurve.setText(_translate("Dialog", "频谱图像", None))
        self.label_4.setText(_translate("Dialog", "设置频率计算范围：", None))
        self.label_7.setText(_translate("Dialog", "MHz", None))
        self.label_8.setText(_translate("Dialog", "MHz", None))
        self.label_14.setText(_translate("Dialog", "设置脉冲计算范围：", None))
        self.label_13.setText(_translate("Dialog", "ms", None))
        self.label_15.setText(_translate("Dialog", "ms", None))
        self.label_2.setText(_translate("Dialog", "-6dB相对带宽", None))
        self.label_5.setText(_translate("Dialog", "脉冲回波灵敏度", None))
        self.label_12.setText(_translate("Dialog", "-20dB相对带宽", None))
        self.label_3.setText(_translate("Dialog", "-6dB高频", None))
        self.label.setText(_translate("Dialog", "探头中心频率", None))
        self.label_11.setText(_translate("Dialog", "-20dB低频", None))
        self.label_10.setText(_translate("Dialog", "-20dB高频", None))
        self.label_9.setText(_translate("Dialog", "-6dB低频", None))
        self.label_6.setText(_translate("Dialog", "脉冲宽度", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

